- name: variablee
  hosts: local
  connection: local
  vars: #play level variables
    GREET: "play"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: enter the values
  #   private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"

    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

#1. COOMAD LINE OR ARGS
#2. task level
#3. files
#4.prompt
#5.