- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle u defined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('Ramesh') }}"


  - name: convert strings into lists
    vars: 
      fruits: "apple , banana , orange" #string
    ansible.builtin.debug:
      msg: "fruits are: {{ fruits | split(',') }}"


  - name: converting map into lists
    vars:
      course: 
        name: ansible
        duration: 10hrs
        trainer: siva
    ansible.builtin.debug:
      msg: " course info: {{ course | dict2items}}"
  
  - name: convert list into map
    vars:
      course: 
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'siva'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"

  - name: covert upper to lower
    vars:
      name: "SivaKumar"
    ansible.builtin.debug:
      msg: "Hello {{ name | lower }}"

  - name: convert lower to upper
    vars:
      name: "VIVEK REDDY BASAM"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"
